"""create channels and channel-members

Revision ID: 313383a1d71e
Revises: af5416bc4195
Create Date: 2026-08-05 00:52:48.988305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313383a1d71e'
down_revision: Union[str, Sequence[str], None] = 'af5416bc4195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('DIRECT', 'GROUP', 'PUBLIC', name='channeltype'), nullable=False),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('channel_members',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'READER', 'EDITOR', 'DIRECT_PARTICIPANT', name='userrole'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.channel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_members')
    op.drop_table('channel')
    # ### end Alembic commands ###
