"""add last_message_text to channel

Revision ID: bcf7a7d3a552
Revises: 01e40d9ebb89
Create Date: 2026-08-11 23:42:43.191040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf7a7d3a552'
down_revision: Union[str, Sequence[str], None] = '01e40d9ebb89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('last_message_text', sa.String(), nullable=True))
    op.add_column('channel', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'last_message_at')
    op.drop_column('channel', 'last_message_text')
    # ### end Alembic commands ###
